### ISSUE TITLE
MyMaid3からの移動

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#3]
1.16.5バージョンアップのためのプラグイン対応作業

**実装を開始する前にこのIssueに「これこれを実装します」と一言コメントしてください**。二人が同時に実装を行うと片方が無駄になります。
★がついている項目は @book000 が実装します。

※: 権限がないと実装が出来ない可能性のある項目
DBを使用している項目でも実装難易度は上がりますができないことはありません。データベーステーブルの情報などほしい場合はご連絡ください。

**現在、各項目を独立した Issue に分割しています。Issue 化されている項目に関してはそちらでステータス管理を行ってください**

## 注意事項

- **開発前に [CONTRIBUTING.md](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読んでください。**
- **開発を開始する前に、`upstream/master` からリベースプルを行い最新状態に追従してください。**
- **[Projects](https://github.com/jaoafa/MyMaid4/projects/1) で、該当する看板があれば `In Progress` に移動してください。**
- **必ずプルリクを送る前にテストサーバで動作テストをしてください。**
- 仕様変更を行ったコマンド・機能は [Discussions の Specification changes](https://github.com/jaoafa/MyMaid4/discussions/94) に記載してください。
- 非推奨となっているメソッドはできる限り推奨メソッドに変更してください。IntelliJの場合取消線が入ります。
- 従来 `MyMaidConfig` で管理していたリストなどの変数は `MyMaidData` に移動する必要があるかもしれません。`CONTRIBUTING.md` に記載している内容の一部を引用しておきます
  - `config.yml` で設定される設定情報は `MyMaidConfig` にあり、 `Main.getMyMaidConfig()` から取得できます。
  - 複数のクラスにわたって使用される変数は `MyMaidData` に変数を作成し、 Getter と Setter を使用して管理してください。
- コマンド・イベントでは指定された場所に配置し、指定されたクラス名でなければ登録されず動作しません。これに違反していてもビルド時のテストで失敗しませんのでご注意ください。
- コマンドでは `CommandPremise` を、イベントでは `Listener` を 実装(`implements`) する必要があります。これをしていない場合、ビルド時のテストで失敗します。

## Commands

- [x] [test](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Test.java) 試験コマンド
- [x] [brb](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Brb.java) バリアブロック取得 #7 
- [x] [cmdb](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Cmdb.java) コマンドブロック取得 #11 
- [x] [ded](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Ded.java) 死んだ場所へのテレポート #12 
- [x] [dedbull](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Dedbull.java) 暗視効果付与・削除 #11 
- [x] [g](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_G.java) ゲームモード変更 #33 
- [x] [getlookloc](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_GetLookLoc.java) 向いている座標のサジェスト→クリップボードへのコピー #33 
- [x] [link](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Link.java) Discordでのlinkコマンド実行誘導 #20 
- [x] [show](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Show.java) 姿を現す #55 
- [x] [hide](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Hide.java) 姿を消す #55 
- [x] [jail](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Jail.java) Jail関連 #59 
- [x] ★[discordlink](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Discordlink.java) Discordアカウント連携 (※DB使用) #62 
- [x] ★[eban](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_EBan.java) EBan関連 (※DB使用) #68 
- [x] ★[history](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_History.java) jaoHistory関連 (※DB使用) #69 
- [x] [chat](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Chat.java) 偽チャット #70 
- [x] ★[chatjail](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_ChatJail.java) ChatJail関連 (※DB使用) #79 
  - ChatBanに名称変更
- [x] ★[getuserkey](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_GetUserKey.java) ユーザーキーの取得 (※DB使用) #80 
  - クリップボードにコピーできるようにする
- [x] [tempmute](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_TempMute.java) 一時的にチャット欄をミュートする #82 
- [x] ★[testment](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Testment.java) Jail時遺言を残す (※DB使用) #172 
- [x] ★[tpdeny](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_TpDeny.java) テレポート禁止関連設定 (※DB使用) #208 
  - remove, notify、プレイヤー名での指定に変更
- [x] [wt](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Wt.java) ワールドテレポート #99 
- [x] ★[bug](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Bug.java) バグ報告 (※Webhookを使用) #319 
- [x] [help](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Help.java) ヘルプブックの入手 #324 
- [x] [convloc](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_ConvLoc.java) 絶対・相対座標変換 #365 
  - クリップボードにコピーできるようにする
- [x] ★[feedback](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Feedback.java) 運営宛てフィードバック (※Webhook使用) 
- [x] [tpalias](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Tpalias.java) テレポートエイリアス関連設定 #366 

### 不要

- [coold](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_coold.java) 旧CPデータの閲覧
- [selclick](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_selclick.java) Shiftしながら空気左クリすると`//sel`コマンドを実行するやつのオンオフ
- [dedrain](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_DedRain.java) 降雨設定
  - gameruleで代用
- [tmt](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Tmt.java) mine_book000になる
- [vercheck](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Vercheck.java) 独自プラグインバージョンチェック
- [workbench](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Workbench.java) 作業台の表示
- [mymaid3](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_MyMaid3.java) プラグインリリース情報表示
  - `mymaid4` コマンドを別用途で実装
- [cauldron](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_Cauldron.java) 大釜設置時の水状態設定

### Discord関連

- [x] [NewPlayerAutoBlMap](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_NewPlayerAutoBlMap.java) 新規がログアウトした際に設置破壊マップをDiscordに送信 #120 
- [x] [FirstLogin](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_FirstLogin.java) 初めてのログイン時にDiscordに通知  #110 
- [x] [PacketLimiterKickNotify](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_PacketLimiterKickNotify.java) パケットリミッターによってキックされた際にDiscordに通知 #254 #256 
- [x] [AdvancementDiscordNotify](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AdvancementDiscordNotify.java) 実績獲得時Discordに通知 #370
- [x] [NotifyTPServerChat](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_NotifyTPServerChat.java) TP時にDiscordサーバチャットに送信 #371

### Discordイベントによる動作

- [x] [Ready](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/DiscordEvent/Event_Ready.java) Ready時処理（Reportチャンネル・jaotanチャンネル・サーバチャットチャンネルの取得） 
- [x] [ServerChatListCmd](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/DiscordEvent/Event_ServerChatListCmd.java) jSAの`/list`コマンド実績用 #83 #240 
- [x] [ServerLeave](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/DiscordEvent/Event_ServerLeave.java) Discordサーバからの退出時に権限リセット設定

### 通知

- [x] [AMHistoryNotify](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AMHistoryNotify.java) ログイン時、jaoHistory記録があればAMに通知
- [ ] [AMVersionCheck](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AMVersionCheck.java) ログイン時、新しいバージョンがあればAMに通知
- [x] [LongTimeNoSee](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_LongTimeNoSee.java) 長期間ログインがなかったユーザーがログインした際に通知 #372 

### 権限による制限

- [x] [CommandLengthLimiter](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CommandLengthLimiter.java) AMRV以外による100バイト越えのコマンド実行制限 #95 
- [x] [SandBoxRegularOnly](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_SandBoxRegularOnly.java) SandBoxでの権限による干渉制限 #113 
- [x] [CommandGameMode](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CommandGameMode.java) AMR以外による他人のゲームモード変更制限 #187 #199 
- [x] [AntiSplashPotion](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AntiSplashPotion.java) 権限に応じてポーション系の利用を制限 #363 

### 全権限対象チャット・コマンド制限

`login`, `sit`, `lay`, `op`, `stop` は `AntiProblemCmd` に纏めること。

- [x] [AntiTargetAllEntityCmd](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AntiTargetAllEntityCmd.java) 全てのエンティティがターゲットとなるセレクタの利用制限 #98
- [x] [CommandTP](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CommandTP.java) `tp`コマンド関連実行制限（他人テレポ・TpDeny・スペクテイター） #197 #208 #164 #191 #197 
- [x] [AntiProblemCmd](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AntiProblemCmd.java) 問題のあるコマンドの利用制限 #42
  - [x] [AntiLoginCmd](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AntiLoginCmd.java) `login`コマンドの制限 #104 
  - [ ] [CheckSimpleSit](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CheckSimpleSit.java) サバイバル時の`sit`,`lay`制限
  - [ ] [CommandOP](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CommandOP.java) `op`コマンド実行制限 #906

### 全権限対象行動制限

- [x] [Antijaoium](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Antijaoium.java) jaoium制限 #103 #284 #286 #328 #347 
- [x] [AntiProblemTeleport](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AntiProblemTeleport.java) 極端に遠い場所へのテレポート制限 #34 
- [x] [AntiNetherPortal](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_AntiNetherPortal.java) ネザーポータルの生成制限 #373

### システム的警告・制限

- [x] [Explosion](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Explosion.java) TNT爆発による絵画等の破壊制限 #99 
- [x] [OldWorldProtection](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_OldWorldProtection.java) 旧ワールドの干渉制限 #251 #257 
- [ ] [Anti4BYTES](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Anti4BYTES.java) 4バイト文字列が看板などに含まれている場合警告 #374 
- [ ] [UseRandomSelector](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_UseRandomSelector.java) AMR以外の`@r`セレクタ使用制限 

### 利便性

- [x] [CommandSendAM](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CommandSendAM.java) AMに実行されたコマンドを通知 #115 

### MyMaidコマンド関連によるイベント

- [x] [Ded](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Ded.java) `ded`コマンド関連 #12 
- [x] [EBan](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_EBan.java) `eban`コマンド関連 (※DB使用) #68 
- [x] [History](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_History.java) `history`コマンド関連 (※DB使用) #69 
- [x] [Jail](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Jail.java) `jail`コマンド関連 (※DB使用) #59 
- [x] [Hide](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Hide.java) `hide`コマンド関連 #55 
- [x] [ChatJail](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_ChatJail.java) ChatJail関連 #79 
- [x] [TempMute](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_TempMute.java) `tempmute`コマンド関連 #82 
- [x] [TeleportAlias](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_TeleportAlias.java) `tpalias`コマンド関連 #366 

### その他

- [x] ★[PlayerCheckPreLogin](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_PlayerCheckPreLogin.java) ログイン前各種チェック (※DB使用) #100 
- [x] ★[Vote](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_Vote.java) 投票関連 (※DB使用) #107 
- [x] ★[LoginSuccessful](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_LoginSuccessful.java) ログイン成功時にDBにそれを書き込み (※DB使用) #106 
- [x] ★[MCBansLoginCheck](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_MCBansLoginCheck.java) MCBansのキャッシュ反映 (※DB使用) #159 #162 
- [x] [NotFadeIce](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_NotFadeIce.java) 氷解けしないようにする #375
- [x] [SpectatorHide](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_SpectatorHide.java) スペクテイター時Dynmapから表示を消すように #452 
- [x] [ViaVerNotify](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_ViaVerNotify.java) ViaVersionからのクライアントバージョン取得・通知 #237 

### 不要

- [TeamDeathMessageCanceler](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_TeamDeathMessageCanceler.java) 動作していない
- [CoOLD](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CoOLD.java) `coold`コマンド関連
- [CPDefectSearcher](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CPDefectSearcher.java) CoreProtectエラーの原因サーチ・警告
- [CommandStop](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_CommandStop.java) `stop`コマンド実行制限
- [EmojiCord](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_EmojiCord.java) EmojiCordの利用制限
- [SignPicStick](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_SignPicStick.java) 棒で叩いた際にSignPictureの内容をチャット欄に表示
- ★[SignLogger](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_SignLogger.java) 看板書き込み情報データベース登録 (※DB使用)
- [PlaceCauldron](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_PlaceCauldron.java) `cauldron`コマンド関連

## Tasks

- [x] [TPSTimings](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_TPSTimings.java) 定期的TPS確認 #193 
- [x] [jaoiumAutoJailRelease](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_jaoiumAutoJailRelease.java) jaoiumによるJailの場合1分後に自動解除する機能 #59 
- [x] [NewStep](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_NewStep.java) jSA2の実績「新たな一歩」 #83 
- [x] [TeleportAlias](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_TeleportAlias.java) tpエイリアス関連 #366 
- [x] [ViaVerNotify](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_ViaVerNotify.java) ViaVersionの参加バージョン通知 #237
- [x] [DisableInvisible](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_DisableInvisible.java) AMR以外による透明無効化 #363 
- [x] [OldWorldCheck](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_OldWorldCheck.java) 旧ワールドがロードしており、プレイヤーがいない場合に自動でアンロードする #738 

### 不要

- [CoOLD](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_CoOLD.java) CoOLDコマンド関連
- [ClearSelection](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_ClearSelection.java) Shiftしながら空気左クリすると`//sel`コマンドを実行する
- [DedRain](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Event/Event_DedRain.java) `dedrain`コマンド関連
- [ ] [AutoRemoveTeam](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Task/Task_AutoRemoveTeam.java) 1人もいないチームを定期的に削除する

## その他

- [x] ★[HTTPServer/VoteFill](https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/HttpServer/Http_VoteFill.java) 投票補填関連 #107 

## その他情報

- [MyMaid4アップデートに関わる更新情報](https://adminwiki.jaoafa.com/ja/upgrade-1_16_5-plugins)
  - 追加するべき項目があったらお知らせください

2021/03/22追記: テストサーバが立ちましたので、DB関連の実装にトライできる可能性があります。もしやりたい人はどうぞ。

**Comment by yuuahp** [comment]
cmdb実装します

**Comment by yuuahp** [comment]
dedbull実装します

**Comment by yuuahp** [comment]
ded実装します

**Comment by yuuahp** [comment]
link実装します

**Comment by yuuahp** [comment]
g実装します

**Comment by yuuahp** [comment]
ClearSelectionやってみます
できるかはわかりません

**Comment by book000** [comment]
2021/03/22追記: テストサーバが立ちましたので、DB関連の実装にトライできる可能性があります。もしやりたい人はどうぞ。

**Comment by yuuahp** [comment]
Getlookloc実装します

**Comment by jojo3926** [comment]
開発部はほとんど全滅状態だがとりあえず俺はそこそこのコマンドを実装して下山するぜ

 AntiProblemTeleportつくる

**Comment by book000** [comment]
マジで開発部ってなんだよ状態だよほんま。いろいろ実装していってくれ

**Comment by yuuahp** [comment]
.

**Comment by jojo3926** [comment]
command stopつくる

**Comment by book000** [comment]
wait

**Comment by book000** [comment]
login, sit, lay, op, stopはAntiProblemCmdにまとめてほしい

**Comment by book000** [comment]
tpだけは面倒な処理結構あるから独立してていいや

**Comment by jojo3926** [comment]
MyMaidconfigにSpam関連の項目を書き加えます
MyMaidLibraryにSpam関連の項目を書き加えます

**Comment by book000** [comment]
Configになんか追加するようなアレあったっけ…まあプルリクきたときにみるわ

**Comment by jojo3926** [comment]
SelectorParserをつくります

**Comment by jojo3926** [comment]
上みっつはライブラリです

**Comment by book000** [comment]
つくるのはいいですがそれぞれでプルリクしてください。一気にやられてもレビューの負担が高すぎます

**Comment by book000** [comment]
原則、1つのコマンド・機能を作ったらそれでプルリク

**Comment by book000** [comment]
![](https://i.imgur.com/Bp3Jt2E.png)
あとSelectorParser不要って言わなかったっけ… @jojo3926

**Comment by jojo3926** [comment]
どこ！？

**Comment by book000** [comment]
あーいや、このSelectorParserは違うわ…とはいえまた別の問題があるのでプルリクで

**Comment by yuuahp** [comment]
ShowHide実装します

**Comment by jojo3926** [comment]
DedRain実装

**Comment by book000** [comment]
以下注意事項を最初のメッセージに追加しました。ご確認ください

- **開発前に [CONTRIBUTING.md](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読んでください。**
- **必ずプルリクを送る前にテストサーバで動作テストをしてください。**
- 開発を開始する前に、`upstream/master` からリベースプルを行い最新状態に追従してください。
- 非推奨となっているメソッドは推奨メソッドに変更してください。IntelliJの場合取消線が入ります。
- 従来 `MyMaidConfig` で管理していたリストなどの変数は `MyMaidData` に移動する必要があるかもしれません。`CONTRIBUTING.md` に記載している内容の一部を引用しておきます
  - `config.yml` で設定される設定情報は `MyMaidConfig` にあり、 `Main.getMyMaidConfig()` から取得できます。
  - 複数のクラスにわたって使用される変数は `MyMaidData` に変数を作成し、 Getter と Setter を使用して管理してください。
- コマンド・イベントでは指定された場所に配置し、指定されたクラス名でなければ登録されず動作しません。これに違反していてもビルド時のテストで失敗しませんのでご注意ください。
- コマンドでは `CommandPremise` を、イベントでは `Listener` を 実装(`implements`) する必要があります。これをしていない場合、ビルド時のテストで失敗します。

**Comment by jojo3926** [comment]
DedRainは実装しないことになってました

**Comment by book000** [comment]
たしかにそうした覚えがあるんだけどどこで書いたっけ…

**Comment by book000** [comment]
eban実装したくね～ぇ…jailからだれかうまく作ってくれねえかなちらっちらっ

**Comment by yuuahp** [comment]
/eban->南の楽園へtpさせる->何もできないようにする->データベースに記述
ですか

**Comment by book000** [comment]
だね、Jailで実装しているものからtestmentを削ったものって感じ

**Comment by yuuahp** [comment]
了解です
今日はAFKParticleな気分なので明日実装してみます

**Comment by book000** [comment]
# convlocコマンドの実装に関する情報

convloc は `command_sheet.txt` ファイルに変換するコマンド一覧を書いて、マッチする場合に変換するようなシステムになっています

変数は

- `%N` は何が入っていてもスキップ
- `%X` は `x` 値
- `%Y` は `y` 値
- `%Z` は `z` 値

になっています。
あとセレクターの `x,y,z` 系の対応

[command_sheet.txt](https://github.com/jaoafa/MyMaid4/files/6204364/command_sheet.txt)

**Comment by yuuahp** [comment]
処罰理由textのSQLインジェクション対策ってどうすればいいですか

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/lib/Jail.java#L106-L111

ここで処理しているので多分大丈夫

**Comment by yuuahp** [comment]
LibJailを真似してEban版を作る感じですか

**Comment by book000** [comment]
y

**Comment by book000** [comment]
まるまるコピペしてJailをEBanに変えて動くならそれでも可

**Comment by yuuahp** [comment]
了解です

**Comment by jojo3926** [comment]
わーるどてれぽ（/wt）つくる

**Comment by book000** [comment]
プルリクは…

**Comment by book000** [comment]
というかプルリクが一度通っていない状態で新規機能つくる場合upstream/master基点でブランチ分けないとどうやったってプルリク通せませんからね。ローカルに残ってしまうので

**Comment by jojo3926** [comment]
直してなかったっけ

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/pull/42#issuecomment-806301378

**Comment by jojo3926** [comment]
Ifが２重になってるやつだよね

**Comment by book000** [comment]
うわなんでoutdatedなのに閉じられてないの

**Comment by book000** [comment]
historyつくるか～

**Comment by yuuahp** [comment]
chat実装します

**Comment by yuuahp** [comment]
chatの本文をStringArrayArgument(可変長引数...?)にしてforeachとかで繋げて送信しようとか思ったんですが、StringArrayArgumentの仕様が全く分かりません...
他にコマンドの引数を全て受け取る方法ありますか?

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/f741197f5b79522a65a560c985fe5dda068d48c8/src/main/java/com/jaoafa/mymaid4/command/Cmd_Jail.java#L48

それ以降の引数を全て受け取る場合 `.greedy` とすればできるみたい。それ以外にダブルクォーテーションで囲んだ引数を一つとみなす `.quoted` 、従来の純粋な一つの引数のみを扱う場合は `.single` (デフォルト) らしい。

**Comment by book000** [comment]
`StringArrayArgument` を使いたいなら公式のサンプルがこのへんかな？

https://github.com/Incendo/cloud/blob/1600ef16c38af1181864880993fdf1cd69dab7f6/examples/example-bukkit/src/main/java/cloud/commandframework/examples/bukkit/ExamplePlugin.java#L389

**Comment by book000** [comment]
あとchatコマンドに関して言えば、ユーザー視点だと `color:xxxxx` のサジェスト欲しいだろうし、それができるなら良いかなあ
できなくてもコマンド引数変えて(後方互換性残した上で)やってもいい

**Comment by yuuahp** [comment]
ありがとうございます🙏
従来通りの書き方ができる方式で作ります

**Comment by book000** [comment]
アップデート予定日が近づいてきました。次のコマンド・機能の実装を優先して行います。

## コマンド

- chatban
- getuserkey
- tempmute
- testment
- tpdeny
- wt

## 機能

- FirstLogin
- NewPlayerAutoBlMap
- PacketLimiterKickNotify
- AMHistoryNotify
- AntiSplashPotion
  - 規制内容に関して要検討
- CommandGameMode
- SandBoxRegularOnly
- AntiProblemCmd の login, sit, lay, op, stop
- AntiTargetAllEntityCmd
- CommandTP
- Antijaoium
- AntiNetherPortal
- Anti4Bytes
- Explosion
- OldWorldProtection
- CommandSendAM
- LoginSuccessful
- MCBansLoginCheck
- NotFadeIce
- PlayerCheckLogin
- SignLogger
- SpectatorHide
- Vote

## その他

- DisableInvisible
- HTTPServer/VoteFill

多いが…。

**Comment by book000** [comment]
chatbanつくります

**Comment by book000** [comment]
getuserkeyつくります

**Comment by book000** [comment]
tempmuteつくります

**Comment by yuuahp** [comment]
CommandLengthLimiterやります

**Comment by yuuahp** [comment]
AntiLoginCmdやります

**Comment by yuuahp** [comment]
AntiTargetAllEntityCmdやります

**Comment by jojo3926** [comment]
Ｅｘｐｌｏｓｉｏｎやります

**Comment by yuuahp** [comment]
PreyerCheckPreLoginやります

**Comment by book000** [comment]
[Project](https://github.com/jaoafa/MyMaid4/projects/1) の `High priority` 項目を優先度順に並び替えました。Projectを確認し、どれを実装するかピックアップしてください。

**Comment by book000** [comment]
Voteに関しては動作確認ができないので、本番投入して動作するか試すしかないです。

**Comment by book000** [comment]
というわけでvoteやります

**Comment by book000** [comment]
**現在、各項目を独立した Issue に分割しています。Issue 化されている項目に関してはそちらでステータス管理を行ってください**

**Comment by book000** [comment]
大部分の実装が完了/個別issue化したのでクローズします。
