### ISSUE TITLE
MyMaid2から全コマンド・機能移転

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#4]
MyMaid2からの移転分

**実装を開始する前にこのIssueに「これこれを実装します」と一言コメントしてください**。二人が同時に実装を行うと片方が無駄になります。
☆が付いている項目は[jaoafa/MyMaid2](https://github.com/jaoafa/MyMaid2)から現在までコードが変わっておらずDBなどを使用していないため、実装できるはずです。ぜひお願いします。
DBを使用している項目でも実装難易度は上がりますができないことはありません。データベーステーブルの情報などほしい場合はご連絡ください。

**現在、各項目を独立した Issue に分割しています。Issue 化されている項目に関してはそちらでステータス管理を行ってください**

## 注意事項

- **開発前に [CONTRIBUTING.md](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読んでください。**
- **開発を開始する前に、`upstream/master` からリベースプルを行い最新状態に追従してください。**
- **[Projects](https://github.com/jaoafa/MyMaid4/projects/1) で、該当する看板があれば `In Progress` に移動してください。**
- **必ずプルリクを送る前にテストサーバで動作テストをしてください。**
- 仕様変更を行ったコマンド・機能は [Discussions の Specification changes](https://github.com/jaoafa/MyMaid4/discussions/94) に記載してください。
- 非推奨となっているメソッドはできる限り推奨メソッドに変更してください。IntelliJの場合取消線が入ります。
- 従来 `MyMaidConfig` で管理していたリストなどの変数は `MyMaidData` に移動する必要があるかもしれません。`CONTRIBUTING.md` に記載している内容の一部を引用しておきます
  - `config.yml` で設定される設定情報は `MyMaidConfig` にあり、 `Main.getMyMaidConfig()` から取得できます。
  - 複数のクラスにわたって使用される変数は `MyMaidData` に変数を作成し、 Getter と Setter を使用して管理してください。
- コマンド・イベントでは指定された場所に配置し、指定されたクラス名でなければ登録されず動作しません。これに違反していてもビルド時のテストで失敗しませんのでご注意ください。
- コマンドでは `CommandPremise` を、イベントでは `Listener` を 実装(`implements`) する必要があります。これをしていない場合、ビルド時のテストで失敗します。

## コマンド

- [x] [delhome](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_delhome.java) ホームの削除 #22 
- [x] [dt](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_dt.java) Dynmapマーカーにテレポートする #44 
- [x] ☆[elytra](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_elytra.java) エリトラと花火を付与 #50 
- [x] ☆[glookup](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_glookup.java) プレイヤーのゲームモードを確認 #33 
- [x] [home](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_home.java) ホームにテレポート #22 
- [x] [player](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_player.java) プレイヤーの権限グループ表示 #17 
- [x] [sethome](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_sethome.java) ホームを設定 #22 
- [x] ☆[rider](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_rider.java) プレイヤー・エンティティに乗る #218 #232 
- [x] ☆[spawn](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_spawn.java) スポーン地点へテレポート #170 
- [x] ☆[hat](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_hat.java) 頭にアイテムを設定 #173 #183 
- [x] ☆[head](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_head.java) 頭を取得 #76 
- [x] [color](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_color.java) 四角色指定 #36 
- [x] ☆[respawn](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_respawn.java) プレイヤーをリスポーン #233 
  - 1.16.5に対応するためにひと手間必要かもしれません
- [x] ☆[messenger](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_messenger.java) 定期メッセージの操作 #134 
- [x] ☆[sign](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_sign.java) 看板の編集 #303 
- [x] ☆[body](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_body.java) ボディにアイテムを設定 #369 
- [x] ☆[boots](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_boots.java) ブーツにアイテムを設定 #369 
- [x] ☆[ck](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_ck.java) 無人トロッコの削除 #236 
  - 多分考え方を考え直したほうがいい気もします。後方互換性を持ったままさらに良い機能になったらいいかなと
- [ ] ☆[enderchest](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_enderchest.java) エンダーチェストの中身を閲覧・編集
- [x] ☆[invedit](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_invedit.java) インベントリを編集 #358 
- [x] ☆[invload](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_invload.java) インベントリをロード #348 
- [x] ☆[invsave](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_invsave.java) インベントリをセーブ #348 
- [x] ☆[invshow](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_invshow.java) インベントリを閲覧 #358 
- [x] ☆[itemedit](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_itemedit.java) アイテム情報を編集 #359 
- [x] ☆[lead](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_lead.java) リードを繋ぐ #367
- [x] ☆[leg](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_leg.java) 脚にアイテムを設定 #369 
- [x] ☆[var](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_var.java) 変数関連操作 #360 
- [x] ☆[wtp](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_wtp.java) ワールド越えテレポート #361 

### 不要

- **selector** セレクタパーステスト
- **votefill** 投票補填
- **restarttitle** タイトルをリセット（外部操作用）
- [mute](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_mute.java) システムメッセージミュート？

### 通知

- [ ] ☆[getUsingMods](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_getUsingMods.java) 使用中Mod情報をAMに通知
- [x] [LoginVoteCheck](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_LoginVoteCheck.java) ログイン時未投票の通知 #362 
- [ ] [PlayerCommandSendRegular](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_PlayerCommandSendRegular.java) Verified以下のコマンド実行をRegularに通知

### 権限による制限

- [x] [AntiPotion](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_AntiPotion.java) ポーション系利用制限（AntiSplashPotion？） #363 
- [x] ☆[QD_NOTSpectator](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_QD_NOTSpectator.java) DVのスペクテイター変更制限 #112 
- [x] [VeryVeryStrongAntiLQD](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_VeryVeryStrongAntiLQD.java) 本来のエンチャ最大値を超えたアイテムの制限 #185 #305 
  - 追加でアイテム属性のチェック機能も実装する

### 全権限対象チャット・コマンド制限

- [ ] ☆[CheckChatOPME](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_CheckChatOPME.java) `opme`メッセージの制限・通知

### 全権限対象行動制限

- [x] ☆[AntiTNTMinecart](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_AntiTNTMinecart.java) TNTカートの利用制限 #364 
- [x] ☆[AntiWither](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_AntiWither.java) ウィザーの出現制限 #116 

### システム関連

- [x] ☆[SKKColor](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_SKKColor.java) チャット・Tabに四角追加 #75 
- [x] [OnlineTime](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_OnlineTime.java) ログイン・ログアウト時、データベースにオンラインタイム情報を登録 #258 
- [x] [JoinHeaderFooterChange](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_JoinHeaderFooterChange.java) ログイン時Tabのフッターとヘッダーを変更 #275 #279 
- [x] [QuitHeaderFooterChange](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_QuitHeaderFooterChange.java) ログアウト時Tabのフッターとヘッダーを削除 #275 #279 
- [ ] [PlayerQuit](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_PlayerQuit.java) ログアウト時データベースに登録 
- [ ] [BanLogger](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_BanLogger.java) Ban関連のデータベース通知・記録
- [x] ☆[LoginLeftPlayerCountNotice](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_LoginLeftPlayerCountNotice.java) ログイン・ログアウト時プレイヤー数をチャット欄に表示 #261 

### 利便性・仕様無効化

- [x] ☆[ChatSpamKickDisable](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_ChatSpamKickDisable.java) スパムによるキック無効化 #256 
  - ChatSpamに限らず要らないキック処理を除外するように変更
- [x] ☆[NOConcretePowderToConcrete](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_NOConcretePowderToConcrete.java) 水によるコンクリパウダーの変化無効化
  - 1.16.5までで追加される外部からの何かで変化するブロックがあればそれも
- [ ] ☆[FarmNOBreak](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_FarmNOBreak.java) 畑の乾き無効化 #368 

### MyMaidコマンド関連によるイベント

- [x] ☆[SignClick](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_SignClick.java) `sign`コマンド関連 #303 #304 
- [x] ☆[CommandBlockVariable](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_CommandBlockVariable.java) 変数`var`コマンド関連 #360 

### 不要

- [ChunkLoad](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_ChunkLoad.java) チャンクロード時4バイト文字列チェック
- [DeathToDeath](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_DeathToDeath.java) 「死」を含むチャット送ったときに殺す
- [LoginTutorialSpawn](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_LoginTutorialSpawn.java) ログイン時チュートリアルにテレポート
- [Shop](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_Shop.java) 独自ショップ
- [Tips](https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_Tips.java) Tipsの表示

## その他情報

- [MyMaid4アップデートに関わる更新情報](https://adminwiki.jaoafa.com/ja/upgrade-1_16_5-plugins)
  - 追加するべき項目があったらお知らせください

2021/03/22追記: よくよく考えたら手を付けていないかなりのコマンド・機能は誰でも開発できる可能性があることに気づきました。ぜひ開発してください

**Comment by book000** [comment]
2021/03/22追記: よくよく考えたら手を付けていないかなりのコマンド・機能は誰でも開発できる可能性があることに気づきました。ぜひ開発してください

**Comment by book000** [comment]
dt実装作業かいし～

**Comment by yuuahp** [comment]
👀glookup実装します

**Comment by yuuahp** [comment]
SKKColorってDB使わないんですか

**Comment by book000** [comment]
使うわ

**Comment by book000** [comment]
なおした👍

**Comment by yuuahp** [comment]
せっかくテストサーバーできたんでSKKColor実装してみたいなと思ったんですがどうですか

**Comment by book000** [comment]
いいよ、いいけど、MyMaid2のこのソースコードと現行で保存方式が変わっているので(2はYAMLファイル保存だったけどDBに移行しているっぽい)、voteテーブルのcolorカラムを使ってほしい
あと、当時の技能的にコードがひどいから(文字連結が最悪)、streamとか昨日のlimitとか使ってログインメッセージの制御とか書き直したほうがいいと思う。可読性が最悪すぎる
結構難易度高いかも。

**Comment by yuuahp** [comment]
やってみます
~~できないかもしれませんが~~

**Comment by book000** [comment]
.

**Comment by yuuahp** [comment]
vote数などが格納されているデータベースとテーブルの構造が知りたいです

**Comment by book000** [comment]
テーブル名: `vote`
![20210322-141726-firefox-OxdGIEOBQL](https://user-images.githubusercontent.com/8929706/111943735-63d0be80-8b19-11eb-8820-ce527ac6e523.png)

**Comment by yuuahp** [comment]
了解です
ありがとうございます🙏

**Comment by yuuahp** [comment]
もしかしてcolorってわざわざ計算しなくてもcolorカラムに格納されてるんですか

**Comment by book000** [comment]
あ、違う。colorカラムは200回数？以上になったときにユーザーが指定できるやつで、指定した色を保持しておくためのカラム。
だからNULL許容でデフォルト値はNULL

**Comment by yuuahp** [comment]
.
なるほど

計算わけわからないので素直に色ごとのifで判定します...

**Comment by book000** [comment]
まあ必要があればプルリク時に修正入れるわ…

**Comment by yuuahp** [comment]
lib.SSKColorManager(Player player)でChatColor返すようにしました
vote数->色の計算もそこにあります

**Comment by book000** [comment]
はいよー

**Comment by yuuahp** [comment]
elytra実装します

**Comment by book000** [comment]
## 注意事項

- **開発前に [CONTRIBUTING.md](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読んでください。**
- **必ずプルリクを送る前にテストサーバで動作テストをしてください。**
- 開発を開始する前に、`upstream/master` からリベースプルを行い最新状態に追従してください。
- 非推奨となっているメソッドは推奨メソッドに変更してください。IntelliJの場合取消線が入ります。
- 従来 `MyMaidConfig` で管理していたリストなどの変数は `MyMaidData` に移動する必要があるかもしれません。`CONTRIBUTING.md` に記載している内容の一部を引用しておきます
  - `config.yml` で設定される設定情報は `MyMaidConfig` にあり、 `Main.getMyMaidConfig()` から取得できます。
  - 複数のクラスにわたって使用される変数は `MyMaidData` に変数を作成し、 Getter と Setter を使用して管理してください。
- コマンド・イベントでは指定された場所に配置し、指定されたクラス名でなければ登録されず動作しません。これに違反していてもビルド時のテストで失敗しませんのでご注意ください。
- コマンドでは `CommandPremise` を、イベントでは `Listener` を 実装(`implements`) する必要があります。これをしていない場合、ビルド時のテストで失敗します。

**Comment by book000** [comment]
アップデート予定日が近づいてきました。次のコマンド・機能の実装を優先して行います。

## コマンド

- color
- ck
- var

## 機能

- VeryVeryStrongAntiLQD
  - クラス名を変えましょう
- AntiTNTMinecart
- AntiWither
- LoginLeftCountNotice
  - → JoinQuitPlayerCountNotify かなあ。
- PlayerQuit
- ChatSpamKickDisable
- FarmNoBreak
- NoConcretePowerToConcrete
- CommandBlockVariable


## その他

- DisableInvisible
- HTTPServer/VoteFill

多いが…。

**Comment by book000** [comment]
messengerつくりもす

**Comment by book000** [comment]
**現在、各項目を独立した Issue に分割しています。Issue 化されている項目に関してはそちらでステータス管理を行ってください**

**Comment by book000** [comment]
大部分の実装が完了/個別issue化したのでクローズします。
